version: "3"

tasks:
  generate:
    desc: Generate mocks and other generated code
    cmds:
      - go generate ./...

  check:
    desc: Check code before pushing to branch
    cmds:
      - go mod tidy
      - gofmt -w .
      - task: generate
      - go test ./...
